apiVersion: v1
kind: Pod
metadata:
  name: gradle-test-pod
spec:
  restartPolicy: Never
  containers:
  - name: gradle-test
    image: gradle-test:1.0
    command: ["gradle", "test"]
    imagePullPolicy : Never
    